#include "Default_Values.h"
/* Place the constant into section FLASH_PARAMS (linker maps it to desired address).
 * Keep `used` attribute so the compiler/linker doesn't discard it even if unused.
 */
//#define FLASH_START_ADDR  (0x0000FE00U)   // Make sure this is valid in Flash

__attribute__((at(INPUT_REG_MIN_START_ADDR))) 
const uint32_t Input_Reg_Min_Start_Addr[] = {
    0,      /* INPUT_MOTOR_STATUS_MIN */
    0,      /* INPUT_FAULT_CODE_MIN */
    0,      /* INPUT_MOTOR_SPEED_MIN */
    0,      /* INPUT_MOTOR_CURRENT_MIN */
    0,      /* INPUT_DC_VOLTAGE_MIN */
    0,      /* INPUT_KW_MIN */
    200,    /* INPUT_WINDING_TEMPERATURE_MIN */
    1338,   /* INPUT_IGBT_TEMPERATURE_MIN */
    0,      /* INPUT_POWER_ON_HOURS_MIN */
    0,      /* INPUT_RUN_HOURS_MIN */
    0,      /* INPUT_DI1_STATUS_MIN */
    0,      /* INPUT_KWH_MIN */
    0,      /* INPUT_RESERVED_13_MIN */
    10000,  /* INPUT_TARGET_SPEED_MODBUS_MIN */
    0,      /* INPUT_FIRE_STATUS_MIN */
    0,      /* INPUT_FAIL_SAFE_STATUS_MIN */
    0,      /* INPUT_FILTER_STATUS_MIN */
    0,      /* INPUT_FILTER_RUN_HOURS_MIN */
    0,      /* INPUT_AI1_VALUE_MIN */
    0,      /* INPUT_AI1_CALCULATED_VALUE_MIN */
    0,      /* INPUT_AI_VALUE_MIN */
    0,      /* INPUT_AI_CALCULATED_VALUE_MIN */
    0,      /* INPUT_RESERVED_3_MIN */
    0,      /* INPUT_RESERVED_4_MIN */
    0,      /* INPUT_LAST_ERROR_CODE_1ST_MIN */
    0,      /* INPUT_LAST_ERROR_CODE_2ND_MIN */
    0,      /* INPUT_LAST_ERROR_CODE_3RD_MIN */
    0,      /* INPUT_LAST_ERROR_CODE_4TH_TIME_MIN */
    0,      /* INPUT_RESERVED_9_MIN */
    0,      /* INPUT_RESERVED_30_MIN */
    0,      /* INPUT_RESERVED_31_MIN */
    0,      /* INPUT_RESERVED_32_MIN */
    0,      /* INPUT_RESERVED_33_MIN */
    0,      /* INPUT_RESERVED_34_MIN */
    0,      /* INPUT_RESERVED_35_MIN */
    0,      /* INPUT_RESERVED_36_MIN */
    0,      /* INPUT_RESERVED_37_MIN */
    0,      /* INPUT_RESERVED_38_MIN */
    0,      /* INPUT_RESERVED_39_MIN */
    0,      /* INPUT_RESERVED_40_MIN */
    0,      /* INPUT_RESERVED_41_MIN */
    0,      /* INPUT_RESERVED_42_MIN */
    0,      /* INPUT_RESERVED_43_MIN */
    0,      /* INPUT_RESERVED_44_MIN */
    0,      /* INPUT_RESERVED_45_MIN */
    0,      /* INPUT_RESERVED_46_MIN */
    0,      /* INPUT_RESERVED_47_MIN */
    0,      /* INPUT_RESERVED_48_MIN */
    0,      /* INPUT_RESERVED_49_MIN */
    0,      /* INPUT_TORQUE_MIN */
    0,      /* INPUT_LOAD_MIN */
    50,     /* INPUT_OPERATING_FREQUENCY_MIN */
    0       /* INPUT_ACUTAL_MOTOR_SPEED_RATED_MIN */
};

	

__attribute__((at(INPUT_REG_MAX_START_ADDR))) 
const uint32_t Input_Reg_Max_Start_Addr[] = {
    4,       /* INPUT_MOTOR_STATUS_MAX */
    65535,   /* INPUT_FAULT_CODE_MAX */
    10000,   /* INPUT_MOTOR_SPEED_MAX */
    2493,    /* INPUT_MOTOR_CURRENT_MAX */
    778,     /* INPUT_DC_VOLTAGE_MAX */
    6000,    /* INPUT_KW_MAX */
    320,     /* INPUT_WINDING_TEMPERATURE_MAX */
    3553,    /* INPUT_IGBT_TEMPERATURE_MAX */
    65535,   /* INPUT_POWER_ON_HOURS_MAX */
    65535,   /* INPUT_RUN_HOURS_MAX */
    1,       /* INPUT_DI1_STATUS_MAX */
    65535,   /* INPUT_KWH_MAX */
    0,       /* INPUT_RESERVED_13_MAX */
    10000,   /* INPUT_TARGET_SPEED_MODBUS_MAX */
    1,       /* INPUT_FIRE_STATUS_MAX */
    1,       /* INPUT_FAIL_SAFE_STATUS_MAX */
    1,       /* INPUT_FILTER_STATUS_MAX */
    65535,   /* INPUT_FILTER_RUN_HOURS_MAX */
    1000,    /* INPUT_AI1_VALUE_MAX */
    10,      /* INPUT_AI1_CALCULATED_VALUE_MAX */
    1000,    /* INPUT_AI_VALUE_MAX */
    20,      /* INPUT_AI_CALCULATED_VALUE_MAX */
    0,       /* INPUT_RESERVED_3_MAX */
    0,       /* INPUT_RESERVED_4_MAX */
    65525,   /* INPUT_LAST_ERROR_CODE_1ST_MAX */
    65525,   /* INPUT_LAST_ERROR_CODE_2ND_MAX */
    65525,   /* INPUT_LAST_ERROR_CODE_3RD_MAX */
    65525,   /* INPUT_LAST_ERROR_CODE_4TH_TIME_MAX */
    0,       /* INPUT_RESERVED_9_MAX */
    0,       /* INPUT_RESERVED_30_MAX */
    0,       /* INPUT_RESERVED_31_MAX */
    0,       /* INPUT_RESERVED_32_MAX */
    0,       /* INPUT_RESERVED_33_MAX */
    0,       /* INPUT_RESERVED_34_MAX */
    0,       /* INPUT_RESERVED_35_MAX */
    0,       /* INPUT_RESERVED_36_MAX */
    0,       /* INPUT_RESERVED_37_MAX */
    0,       /* INPUT_RESERVED_38_MAX */
    0,       /* INPUT_RESERVED_39_MAX */
    0,       /* INPUT_RESERVED_40_MAX */
    0,       /* INPUT_RESERVED_41_MAX */
    0,       /* INPUT_RESERVED_42_MAX */
    0,       /* INPUT_RESERVED_43_MAX */
    0,       /* INPUT_RESERVED_44_MAX */
    0,       /* INPUT_RESERVED_45_MAX */
    0,       /* INPUT_RESERVED_46_MAX */
    0,       /* INPUT_RESERVED_47_MAX */
    0,       /* INPUT_RESERVED_48_MAX */
    0,       /* INPUT_RESERVED_49_MAX */
    750,     /* INPUT_TORQUE_MAX */
    100,     /* INPUT_LOAD_MAX */
    60,      /* INPUT_OPERATING_FREQUENCY_MAX */
    10000    /* INPUT_ACUTAL_MOTOR_SPEED_RATED_MAX */
};

	

__attribute__((at(HOLDING_REG_MAX_START_ADDR))) 
const uint32_t Holding_Reg_Max_Start_Addr[] = {
    254,    /* HOLDING_NODE_ADDRESS_MAX */
    5,      /* HOLDING_BAUD_RATE_MAX */
    2,      /* HOLDING_PARITY_SET_MAX */
    1,      /* HOLDING_STOP_BIT_MAX */
    3,      /* HOLDING_CONTROL_MODE_MAX */
    10000,  /* HOLDING_SET_SPEED_IN_MODBUS_SIGNAL_LOSS_MODE_MAX */
    10000,  /* HOLDING_SET_SPEED_IN_FIRE_ALARAM_MODE_MAX */
    10000,  /* HOLDING_MAXIMUM_SPEED_MAX */
    10000,  /* HOLDING_TARGET_SPEED_FROM_MODBUS_MAX */
    1,      /* HOLDING_FAN_ROTATION_MAX */
    1000,   /* HOLDING_RAMP_UP_TIME_MAX */
    1000,   /* HOLDING_RAMP_DOWN_TIME_MAX */
    1,      /* HOLDING_FIRE_ALARM_MODE_SOURCE_MAX */
    1,      /* HOLDING_FIRE_ALARM_ACTIVATE_MAX */
    1,      /* HOLDING_DI1_FUNCTION_MAX */
    1,      /* HOLDING_DI2_FUNCTION_MAX */
    5000,   /* HOLDING_SET_FILTER_RUN_HOURS_MAX */
    1,      /* HOLDING_RESET_FILTER_RUN_HOURS_MAX */
    10000,  /* HOLDING_AI1_MINIMUM_VALUE_MAX */
    12000,  /* HOLDING_SWITCHING_FREQUENCY_MAX */
    10000,  /* HOLDING_AI1_MAXIMUM_VALUE_MAX */
    4,      /* HOLDING_PID_SENSOR_SELECT_MAX */
    0,      /* HOLDING_RESERVED_23_MAX */
    1,      /* HOLDING_PID_SENSOR_SELECT_MAX */
    0,      /* HOLDING_RESERVED_25_MAX */
    0,      /* HOLDING_RESERVED_26_MAX */
    0,      /* HOLDING_RESERVED_27_MAX */
    0,      /* HOLDING_RESERVED_28_MAX */
    0,      /* HOLDING_RESERVED_29_MAX */
    0,      /* HOLDING_RESERVED_30_MAX */
    1,      /* HOLDING_SET_DEFAULT_FACTORY_MAX */
    10000,  /* HOLDING_VIB_FREQUENCY_REG_1_MAX */
    10000,  /* HOLDING_VIB_FREQUENCY_REG_2_MAX */
    10000,  /* HOLDING_VIB_FREQUENCY_REG_3_MAX */
    10000,  /* HOLDING_VIB_FREQUENCY_REG_4_MAX */
    10000,  /* HOLDING_VIB_FREQUENCY_REG_5_MAX */
    10000,  /* HOLDING_VIB_FREQUENCY_REG_6_MAX */
    10000,  /* HOLDING_VIB_FREQUENCY_REG_7_MAX */
    10000,  /* HOLDING_VIB_FREQUENCY_REG_8_MAX */
    10000,  /* HOLDING_VIB_FREQUENCY_REG_9_MAX */
    10000,  /* HOLDING_VIB_FREQUENCY_REG_10_MAX */
    10000,  /* HOLDING_VIB_FREQUENCY_REG_11_MAX */
    10000,  /* HOLDING_VIB_FREQUENCY_REG_12_MAX */
    10000,  /* HOLDING_VIB_FREQUENCY_REG_13_MAX */
    10000,  /* HOLDING_VIB_FREQUENCY_REG_14_MAX */
    10000,  /* HOLDING_VIB_FREQUENCY_REG_15_MAX */
    2,      /* HOLDING_BMS_FUNCTION_MAX */
    15,     /* HOLDING_SUPPRESSION_RANGE_SETTING_MAX */
    10000,  /* HOLDING_RANGE_MIN_SPEED_MAX */
    10000,  /* HOLDING_RANGE_MAX_SPEED_MAX */
    90,     /* HOLDING_RANGE_MIN_WINDING_TEMPERATUE_MAX */
    70,     /* HOLDING_RANGE_MAX_WINDING_TEMPERATUE_MAX */
    2493,   /* HOLDING_RANGE_MIN_MOTOR_CURRENT_MAX */
    2493,   /* HOLDING_RANGE_MAX_MOTOR_CURRENT_MAX */
    1,      /* HOLDING_PID_CONFIGURATION_DIFFERENTIAL_PRESSURE_SET_VALUE_MAX */
    1,      /* HOLDING_DIFFERENTIAL_PRESSURE_RANGE_MIN_MAX */
    1,      /* HOLDING_DIFFERNETIAL_PRESEURE_RANGE_MAX_MAX */
    1,      /* HOLDING_PRESSURE_SPEED_MIN_MAX */
    1,      /* HOLDING_PRESSURE_SPEED_MAX_MAX */
    1,      /* HOLDING_PID_CONFIGURATION_DIFFERNETIAL_TEMPERAUTE_SET_VALUE_MAX */
    1,      /* HOLDING_RESERVED_61_MAX */
    1,      /* HOLDING_RESERVED_62_MAX */
    1,      /* HOLDING_DIFFERNTIAL_TEMPERATURE_SPEED_MIN_MAX */
    1,      /* HOLDING_DIFFERNTIAL_TEMPERATURE_SPEED_MAX_MAX */
    1,      /* HOLDING_PID_CONFIGURE_FLOW_RATE_SET_VALUE_MAX */
    1,      /* HOLDING_FLOW_RATE_RANGE_MIN_MAX */
    1,      /* HOLDING_FLOW_RATE_RANGE_MAX_MAX */
    1,      /* HOLDING_FLOW_SPEED_MIN_MAX */
    1,      /* HOLDING_FLOW_SPEED_MAX_MAX */
    1,      /* HOLDING_K1_FUNCTION_MAX */
    10000,  /* HOLDING_SET_INTERNAL_1_MAX */
    10000,  /* HOLDING_SET_INTERNAL_2_MAX */
    10000,  /* HOLDING_SET_INTERNAL_3_MAX */
    10000,  /* HOLDING_MIN_SPEED_MAX */
    65535,  /* HOLDING_RESERVED_75_MAX */
    1,      /* HOLDING_CONTROL_BITS_MAX */
    3,      /* HOLDING_RESERVED_77_MAX */
    1,      /* HOLDING_LED_MODE_MAX */
    3,      /* HOLDING_TMPMGMT_MAX */
    1,      /* HOLDING_MIDSPEED_OFF_MAX */
    0,      /* HOLDING_RESERVED_81_MAX */
    0,      /* HOLDING_RESERVED_82_MAX */
    0,      /* HOLDING_RESERVED_83_MAX */
    0,      /* HOLDING_RESERVED_84_MAX */
    0,      /* HOLDING_RESERVED_85_MAX */
    0,      /* HOLDING_RESERVED_86_MAX */
    0,      /* HOLDING_RESERVED_87_MAX */
    0,      /* HOLDING_RESERVED_88_MAX */
    0,      /* HOLDING_RESERVED_89_MAX */
    1,      /* HOLDING_BLOCKING_PROTECTION_CHANGE_OF_DIRECTION_MAX */
    5,      /* HOLDING_RESERVED_91_MAX */
    1,      /* HOLDING_RESET_MAX */
    1,      /* HOLDING_ANTI_LOCK_RETIES_ROTOR_LOCK_MAX */
    1,      /* HOLDING_SYSTEM_DESIGNER_MAX */
    1,      /* HOLDING_END_CUSTOMER_MAX */
    1,      /* HOLDING_SENSOR_PRESSURE_UNIT_MAX */
    1,      /* HOLDING_SENSOR_TEMPERATURE_UNIT_MAX */
    1,      /* HOLDING_SENSOR_FLOW_UNIT_MAX */
    0,      /* HOLDING_RESERVED_99_MAX */
    0,      /* HOLDING_RESERVED_100_MAX */
    0,      /* HOLDING_RESERVED_101_MAX */
    1,      /* HOLDING_SYSTEM_ADMINISTRATOR_MAX */
    0,      /* HOLDING_RESERVED_103_MAX */
    65535,  /* HOLDING_MOTOR_MODEL_NAME_104_MAX */
    65535,  /* HOLDING_MOTOR_MODEL_NAME_105_MAX */
    65535,  /* HOLDING_MOTOR_MODEL_NAME_106_MAX */
    65535,  /* HOLDING_MOTOR_MODEL_NAME_107_MAX */
    65535,  /* HOLDING_MOTOR_MODEL_NAME_108_MAX */
    65535,  /* HOLDING_MOTOR_MODEL_NAME_109_MAX */
    65535,  /* HOLDING_MOTOR_MODEL_NAME_110_MAX */
    65535,  /* HOLDING_MOTOR_MODEL_NAME_111_MAX */
    65535,  /* HOLDING_MOTOR_MACHINE_NUMBER_112_MAX */
    65535,  /* HOLDING_MOTOR_MACHINE_NUMBER_113_MAX */
    65535,  /* HOLDING_MOTOR_MACHINE_NUMBER_114_MAX */
    65535,  /* HOLDING_MOTOR_MACHINE_NUMBER_115_MAX */
    65535,  /* HOLDING_MOTOR_MACHINE_NUMBER_116_MAX */
    65535,  /* HOLDING_MOTOR_MACHINE_NUMBER_117_MAX */
    65535,  /* HOLDING_MOTOR_PRODUCTION_YEAR_MAX */
    65535,  /* HOLDING_MOTOR_PRODUCTION_MONTH_MAX */
    65535,  /* HOLDING_MOTOR_PRODUCTION_DAY_MAX */
    65535,  /* HOLDING_MODEL_NAME_121_MAX */
    65535,  /* HOLDING_MODEL_NAME_122_MAX */
    65535,  /* HOLDING_MODEL_NAME_123_MAX */
    65535,  /* HOLDING_MODEL_NAME_124_MAX */
    65535,  /* HOLDING_MODEL_NAME_125_MAX */
    65535,  /* HOLDING_MODEL_NAME_126_MAX */
    65535,  /* HOLDING_MODEL_NAME_127_MAX */
    65535,  /* HOLDING_MODEL_NAME_128_MAX */
    65535,  /* HOLDING_MACHINE_NUMBER_129_MAX */
    65535,  /* HOLDING_MACHINE_NUMBER_130_MAX */
    65535,  /* HOLDING_MACHINE_NUMBER_131_MAX */
    65535,  /* HOLDING_MACHINE_NUMBER_132_MAX */
    65535,  /* HOLDING_MACHINE_NUMBER_133_MAX */
    65535,  /* HOLDING_MACHINE_NUMBER_134_MAX */
    65535,  /* HOLDING_MACHINE_PRODUCTION_YEAR_MAX */
    65535,  /* HOLDING_MACHINE_PRODUCITON_MONTH_MAX */
    65535,  /* HOLDING_MACHINE_PRODUCITON_DAY_MAX */
    6000,   /* HOLDING_RATED_POWER_RATING_MAX */
    0,      /* HOLDING_RESERVED_139_MAX */
    0,      /* HOLDING_RESERVED_140_MAX */
    2498,   /* HOLDING_RATED_CURRENT_MAX */
    0,      /* HOLDING_RESERVED_142_MAX */
    20,     /* HOLDING_NO_OF_POLES_MAX */
    0,      /* HOLDING_RESERVED_144_MAX */
    750,    /* HOLDING_RATED_TORQUE_MAX */
    0,      /* HOLDING_DRIVE_INPUT_VOLTAGE_MIN_RANGE_MAX */
    6000,   /* HOLDING_DRIVE_MAXIMUM_OUTPUT_MAX_POWER_MAX */
    2498,   /* HOLDING_DRIVE_MAXIMUM_CURRENT_RATING_MAX */
    60,     /* HOLDING_DRIVE_FRQUENCY_MAX_RANGE_MAX */
    320,    /* HOLDING_TEMPERATURE_MIN_WORKING_RANGE_MAX */
    200,    /* HOLDING_TEMPERATURE_MAX_WORKING_RANGE_MAX */
    1339,   /* HOLDING_RANGE_MIN_IGBT_TEMPERATUE_MAX */
    3553,   /* HOLDING_RANGE_MAX_IGBT_TEMPERATUE_MAX */
    778,    /* HOLDING_DRIVE_INPUT_VOLTAGE_MAX_RANGE_MAX */
    0,      /* HOLDING_DRIVE_FRQUENCY_MIN_RANGE_MAX */
    16000,  /* HOLDING_INPUT_FREQUENCY_MAX_RANGE_MAX */
    50,     /* HOLDING_INPUT_FREQUENCY_MIN_RANE_MAX */
    1,      /* HOLDING_TORQUE_CONSTANT_MAX */
    1,      /* HOLDING_FAIL_SAFE_ON_OFF_MAX */
    2,      /* HOLDING_FAIL_SAFE_RUNNING_DIRECTION_MAX */
    10000,  /* HOLDING_FAIL_SAFE_FUNCTION_SET_SPEED_MAX */
    1,      /* HOLDING_FAIL_SAFE_SOURCE_MAX */
    2       /* HOLDING_FAIL_SAFE_ACTIVATE_SET_VALUE_MAX */
};

__attribute__((at(HOLDING_REG_MIN_START_ADDR))) 
const uint32_t Holding_Reg_Min_Start_Addr[] = {
	1,/*HOLDING_NODE_ADDRESS_MIN*/
	0,/*HOLDING_BAUD_RATE_MIN*/
	0,/*HOLDING_PARITY_SET_MIN*/
	0,/*HOLDING_STOP_BIT_MIN*/
	0,/*HOLDING_CONTROL_MODE_MIN*/
	10000,/*HOLDING_SET_SPEED_IN_MODBUS_SIGNAL_LOSS_MODE_MIN*/
	10000,/*HOLDING_SET_SPEED_IN_FIRE_ALARAM_MODE_MIN*/
	10000,/*HOLDING_MINIMUM_SPEED_MIN*/
	10000,/*HOLDING_TARGET_SPEED_FROM_MODBUS_MIN*/
	0	,/*HOLDING_FAN_ROTATION_MIN*/
	0	,/*HOLDING_RAMP_UP_TIME_MIN*/
	0	,/*HOLDING_RAMP_DOWN_TIME_MIN*/
	0	,/*HOLDING_FIRE_ALARM_MODE_SOURCE_MIN*/
	0	,/*HOLDING_FIRE_ALARM_ACTIVATE_MIN*/
	0	,/*HOLDING_DI1_FUNCTION_MIN*/
	0	,/*HOLDING_DI2_FUNCTION_MIN*/
	0	,/*HOLDING_SET_FILTER_RUN_HOURS_MIN*/
	0	,/*HOLDING_RESET_FILTER_RUN_HOURS_MIN*/
	0	,/*HOLDING_AI1_MINIMUM_VALUE_MIN*/
	0,/*HOLDING_SWITCHING_FREQUENCY_MIN*/
	0,/*HOLDING_AI1_MINIMUM_VALUE_MIN*/
	0,/*HOLDING_PID_SENSOR_SELECT_MIN*/     //PID REGISTER 
	0,/*HOLDING_RESERVED_23_MIN*/
	0,/*HOLDING_RESERVED_24_MIN*/
	0,/*HOLDING_RESERVED_25_MIN*/
	0,/*HOLDING_RESERVED_26_MIN*/
	0,/*HOLDING_RESERVED_27_MIN*/
	0,/*HOLDING_RESERVED_28_MIN*/
	0,/*HOLDING_RESERVED_29_MIN*/
	0,/*HOLDING_RESERVED_30_MIN*/
	10000,/*HOLDING_SET_DEFAULT_FACTORY_MIN*/
	10000,/*HOLDING_VIB_FREQUENCY_REG_1_MIN*/
	10000,/*HOLDING_VIB_FREQUENCY_REG_2_MIN*/
	10000,/*HOLDING_VIB_FREQUENCY_REG_3_MIN*/
	10000,/*HOLDING_VIB_FREQUENCY_REG_4_MIN*/
	10000,/*HOLDING_VIB_FREQUENCY_REG_5_MIN*/
	10000,/*HOLDING_VIB_FREQUENCY_REG_6_MIN*/
	10000,/*HOLDING_VIB_FREQUENCY_REG_7_MIN*/
	10000,/*HOLDING_VIB_FREQUENCY_REG_8_MIN*/
	10000,/*HOLDING_VIB_FREQUENCY_REG_9_MIN*/
	10000,/*HOLDING_VIB_FREQUENCY_REG_10_MIN*/
	10000,/*HOLDING_VIB_FREQUENCY_REG_11_MIN*/
	10000,/*HOLDING_VIB_FREQUENCY_REG_12_MIN*/
	10000,/*HOLDING_VIB_FREQUENCY_REG_13_MIN*/
	10000,/*HOLDING_VIB_FREQUENCY_REG_14_MIN*/
	10000,/*HOLDING_VIB_FREQUENCY_REG_15_MIN*/
	0,/*HOLDING_BMS_FUNCTION_MIN*/
	0,/*HOLDING_SUPPRESSION_RANGE_SETTING_MIN*/
	0,/*HOLDING_RANGE_MIN_SPEED_MIN*/
	0,/*HOLDING_RANGE_MIN_SPEED_MIN*/
	0,/*HOLDING_RANGE_MIN_WINDING_TEMPERATUE_MIN*/
	0,/*HOLDING_RANGE_MIN_WINDING_TEMPERATUE_MIN*/
	0,/*HOLDING_RANGE_MIN_MOTOR_CURRENT_MIN*/
	0	,/*HOLDING_RANGE_MIN_MOTOR_CURRENT_MIN*/
	0,/*HOLDING_PID_CONFIGURATION_DIFFERENTIAL_PRESSURE_SET_VALUE_MIN*/
	0,/*HOLDING_DIFFERENTIAL_PRESSURE_RANGE_MIN_MIN*/
	0,/*HOLDING_DIFFERNETIAL_PRESEURE_RANGE_MIN_MIN*/
	0,/*HOLDING_PRESSURE_SPEED_MIN_MIN*/
	0,/*HOLDING_PRESSURE_SPEED_MIN_MIN*/
	0,/*HOLDING_PID_CONFIGURATION_DIFFERNETIAL_TEMPERAUTE_SET_VALUE_MIN*/
	0,/*HOLDING_RESERVED_61_MIN*/
	0,/*HOLDING_RESERVED_62_MIN*/
	0,/*HOLDING_DIFFERNTIAL_TEMPERATURE_SPEED_MIN_MIN*/
	0,/*HOLDING_DIFFERNTIAL_TEMPERATURE_SPEED_MIN_MIN*/
	0,/*HOLDING_PID_CONFIGURE_FLOW_RATE_SET_VALUE_MIN*/
	0,/*HOLDING_FLOW_RATE_RANGE_MIN_MIN*/
	0,/*HOLDING_FLOW_RATE_RANGE_MIN_MIN*/
	0,/*HOLDING_FLOW_SPEED_MIN_MIN*/
	0,/*HOLDING_FLOW_SPEED_MIN_MIN*/
	0,/*HOLDING_K1_FUNCTION_MIN*/
	0,/*HOLDING_SET_INTERNAL_1_MIN*/
	0,/*HOLDING_SET_INTERNAL_2_MIN*/
	0,/*HOLDING_SET_INTERNAL_3_MIN*/
	0,/*HOLDING_MIN_SPEED_MIN*/
	0,/*HOLDING_RESERVED_75_MIN*/
	0,/*HOLDING_CONTROL_BITS_MIN*/
	0,/*HOLDING_RESERVED_77_MIN*/
	0,/*HOLDING_LED_MODE_MIN*/
	0,/*HOLDING_RESERVED_79_MIN*/
	0,/*HOLDING_RESERVED_80_MIN*/
	0,/*HOLDING_RESERVED_81_MIN*/
	0,/*HOLDING_RESERVED_82_MIN*/
	0,/*HOLDING_RESERVED_83_MIN*/
	0,/*HOLDING_RESERVED_84_MIN*/
	0,/*HOLDING_RESERVED_85_MIN*/
	0,/*HOLDING_RESERVED_86_MIN*/
	0,/*HOLDING_RESERVED_87_MIN*/
	0,/*HOLDING_RESERVED_88_MIN*/
	0,/*HOLDING_RESERVED_89_MIN*/
	0,/*HOLDING_BLOCKING_PROTECTION_CHANGE_OF_DIRECTION_MIN*/
	0,/*HOLDING_RESERVED_91_MIN*/
	0,/*HOLDING_RESET_MIN*/
	0,/*HOLDING_ANTI_LOCK_RETIES_ROTOR_LOCK_MIN*/
	0,/*HOLDING_SYSTEM_DESIGNER_MIN*/
	0,/*HOLDING_END_CUSTOMER_MIN*/
	0,/*HOLDING_SENSOR_PRESSURE_UNIT_MIN*/
	0,/*HOLDING_SENSOR_TEMPERATURE_UNIT_MIN*/
	0,/*HOLDING_SENSOR_FLOW_UNIT_MIN*/
	0,/*HOLDING_RESERVED_99_MIN*/
	0,/*HOLDING_RESERVED_100_MIN*/
	0,/*HOLDING_RESERVED_101_MIN*/
	0,/*HOLDING_SYSTEM_ADMINISTRATOR_MIN*/
	0,/*HOLDING_RESERVED_103_MIN*/
	0,/*HOLDING_MOTOR_MODEL_NAME_104_MIN*/
	0,/*HOLDING_MOTOR_MODEL_NAME_105_MIN*/
	0,/*HOLDING_MOTOR_MODEL_NAME_106_MIN*/
	0,/*HOLDING_MOTOR_MODEL_NAME_107_MIN*/
	0,/*HOLDING_MOTOR_MODEL_NAME_108_MIN*/
	0,/*HOLDING_MOTOR_MODEL_NAME_109_MIN*/
	0,/*HOLDING_MOTOR_MODEL_NAME_110_MIN*/
	0,/*HOLDING_MOTOR_MODEL_NAME_111_MIN*/
	0,/*HOLDING_MOTOR_MACHINE_NUMBER_112_MIN*/
	0,/*HOLDING_MOTOR_MACHINE_NUMBER_113_MIN*/
	0,/*HOLDING_MOTOR_MACHINE_NUMBER_114_MIN*/
	0,/*HOLDING_MOTOR_MACHINE_NUMBER_115_MIN*/
	0,/*HOLDING_MOTOR_MACHINE_NUMBER_116_MIN*/
	0,/*HOLDING_MOTOR_MACHINE_NUMBER_117_MIN*/
	0,/*HOLDING_MOTOR_PRODUCTION_YEAR_MIN*/
	0,/*HOLDING_MOTOR_PRODUCTION_MONTH_MIN*/
	0,/*HOLDING_MOTOR_PRODUCTION_DAY_MIN*/
	0,/*HOLDING_MODEL_NAME_121_MIN*/
	0,/*HOLDING_MODEL_NAME_122_MIN*/
	0,/*HOLDING_MODEL_NAME_123_MIN*/
	0,/*HOLDING_MODEL_NAME_124_MIN*/
	0,/*HOLDING_MODEL_NAME_125_MIN*/
	0,/*HOLDING_MODEL_NAME_126_MIN*/
	0,/*HOLDING_MODEL_NAME_127_MIN*/
	0,/*HOLDING_MODEL_NAME_128_MIN*/
	0,/*HOLDING_MACHINE_NUMBER_129_MIN*/
	0,/*HOLDING_MACHINE_NUMBER_130_MIN*/
	0,/*HOLDING_MACHINE_NUMBER_131_MIN*/
	0,/*HOLDING_MACHINE_NUMBER_132_MIN*/
	0,/*HOLDING_MACHINE_NUMBER_133_MIN*/
	0,/*HOLDING_MACHINE_NUMBER_134_MIN*/
	0,/*HOLDING_MACHINE_PRODUCTION_YEAR_MIN*/
	0,/*HOLDING_MACHINE_PRODUCITON_MONTH_MIN*/
	0,/*HOLDING_MACHINE_PRODUCITON_DAY_MIN*/
	0,/*HOLDING_RATED_POWER_RATING_MIN*/
	0,/*HOLDING_RESERVED_139_MIN*/
	0,/*HOLDING_RESERVED_140_MIN*/
	0,/*HOLDING_RATED_CURRENT_MIN*/
	0,/*HOLDING_RESERVED_142_MIN*/
	2,/*HOLDING_NO_OF_POLES_MIN*/
	0,/*HOLDING_RESERVED_144_MIN*/
	0,/*HOLDING_RATED_TORQUE_MIN*/
	0,/*HOLDING_DRIVE_INPUT_VOLTAGE_MIN_RANGE_MIN*/
	0,/*HOLDING_DRIVE_MINIMUM_OUTPUT_MIN_POWER_MIN*/
	0,/*HOLDING_DRIVE_MINIMUM_CURRENT_RATING_MIN*/
	0,/*HOLDING_DRIVE_FRQUENCY_MIN_RANGE_MIN*/
	0,/*HOLDING_TEMPERATURE_MIN_WORKING_RANGE_MIN*/
	0,/*HOLDING_TEMPERATURE_MIN_WORKING_RANGE_MIN*/
	0,/*HOLDING_RANGE_MIN_IGBT_TEMPERATUE_MIN*/
	0,/*HOLDING_RANGE_MIN_IGBT_TEMPERATUE_MIN*/
	0,/*HOLDING_DRIVE_INPUT_VOLTAGE_MIN_RANGE_MIN*/
	0,/*HOLDING_DRIVE_FRQUENCY_MIN_RANGE_MIN*/
	0,/*HOLDING_INPUT_FREQUENCY_MIN_RANGE_MIN*/
	0,/*HOLDING_INPUT_FREQUENCY_MIN_RANE_MIN*/
	0,/*HOLDING_TORQUE_CONSTANT_MIN*/
	0,/*HOLDING_FAIL_SAFE_ON_OFF_MIN*/
	0,/*HOLDING_FAIL_SAFE_RUNNING_DIRECTION_MIN*/
	0,/*HOLDING_FAIL_SAFE_FUNCTION_SET_SPEED_MIN*/
	0,/*HOLDING_FAIL_SAFE_SOURCE_MIN*/
	0,/*HOLDING_FAIL_SAFE_ACTIVATE_SET_VALUE_MIN*/
	0,/*HOLDING_TOTAL_MEMBER_MIN*/
	};
		
	__attribute__((at(HOLDING_REG_DEFAULT_START_ADDR))) 
const uint32_t Holding_Reg_Default_Start_Addr[] = {
		1,/*HOLDING_NODE_ADDRESS_DEFAULT*/
		2,/*HOLDING_BAUD_RATE_DEFAULT*/
		0,/*HOLDING_PARITY_SET_DEFAULT*/
		0,/*HOLDING_STOP_BIT_DEFAULT*/
		1,/*HOLDING_CONTROL_MODE_DEFAULT*/
		1800,/*HOLDING_SET_SPEED_IN_MODBUS_SIGNAL_LOSS_MODE_DEFAULT*/
		1800,/*HOLDING_SET_SPEED_IN_FIRE_ALARAM_MODE_DEFAULT*/
		1800,/*HOLDING_DEFAULTIMUM_SPEED_DEFAULT*/
		100,/*HOLDING_TARGET_SPEED_FROM_MODBUS_DEFAULT*/
		0,/*HOLDING_FAN_ROTATION_DEFAULT*/
		10,/*HOLDING_RAMP_UP_TIME_DEFAULT*/
		10,/*HOLDING_RAMP_DOWN_TIME_DEFAULT*/
		0,/*HOLDING_FIRE_ALARM_MODE_SOURCE_DEFAULT*/
		0,/*HOLDING_FIRE_ALARM_ACTIVATE_DEFAULT*/
		1,/*HOLDING_DI1_FUNCTION_DEFAULT*/
		0,/*HOLDING_DI2_FUNCTION_DEFAULT*/
		720,/*HOLDING_SET_FILTER_RUN_HOURS_DEFAULT*/
		0,/*HOLDING_RESET_FILTER_RUN_HOURS_DEFAULT*/
		2,/*HOLDING_AI1_DEFAULTIMUM_VALUE_DEFAULT*/
		12000,/*HOLDING_SWITCHING_FREQUENCY_DEFAULT*/
		8,/*HOLDING_AI1_DEFAULTIMUM_VALUE_DEFAULT*/
		0,/*HOLDING_PID_SENSOR_SELECT_DEFAULT*/     //PID REGISTER 
		0,/*HOLDING_RESERVED_23_DEFAULT*/
		0,/*HOLDING_RESERVED_24_DEFAULT*/
		1,/*HOLDING_RESERVED_25_DEFAULT*/
		0,/*HOLDING_RESERVED_26_DEFAULT*/
		0,/*HOLDING_RESERVED_27_DEFAULT*/
		0,/*HOLDING_RESERVED_28_DEFAULT*/
		0,/*HOLDING_RESERVED_29_DEFAULT*/
		0,/*HOLDING_RESERVED_30_DEFAULT*/
		0,/*HOLDING_SET_DEFAULT_FACTORY_DEFAULT*/
		400,/*HOLDING_RESERVED_32_DEFAULT*/
		525,/*HOLDING_RESERVED_33_DEFAULT*/
		650,/*HOLDING_RESERVED_34_DEFAULT*/
		775,/*HOLDING_RESERVED_35_DEFAULT*/
		900,/*HOLDING_RESERVED_36_DEFAULT*/
		1025,/*HOLDING_RESERVED_37_DEFAULT*/
		1150,/*HOLDING_RESERVED_38_DEFAULT*/
		1275,/*HOLDING_RESERVED_39_DEFAULT*/
		1400,/*HOLDING_RESERVED_40_DEFAULT*/
		1525,/*HOLDING_RESERVED_41_DEFAULT*/
		1650,/*HOLDING_RESERVED_42_DEFAULT*/
		1775,/*HOLDING_RESERVED_43_DEFAULT*/
		1900,/*HOLDING_RESERVED_44_DEFAULT*/
		2025,/*HOLDING_RESERVED_45_DEFAULT*/
		2150,/*HOLDING_RESERVED_46_DEFAULT*/
		0,/*HOLDING_BMS_FUNCTION_DEFAULT*/
		0,/*HOLDING_SUPPRESSION_RANGE_SETTING_DEFAULT*/
		300,/*HOLDING_RANGE_DEFAULT_SPEED_DEFAULT*/
		450,/*HOLDING_RANGE_DEFAULT_SPEED_DEFAULT*/
		0,/*HOLDING_RANGE_DEFAULT_WINDING_TEMPERATUE_DEFAULT*/
		0,/*HOLDING_RANGE_DEFAULT_WINDING_TEMPERATUE_DEFAULT*/
		0,/*HOLDING_RANGE_DEFAULT_MOTOR_CURRENT_DEFAULT*/
		0,/*HOLDING_RANGE_DEFAULT_MOTOR_CURRENT_DEFAULT*/
		0,/*HOLDING_PID_CONFIGURATION_DIFFERENTIAL_PRESSURE_SET_VALUE_DEFAULT*/
		0,/*HOLDING_DIFFERENTIAL_PRESSURE_RANGE_DEFAULT_DEFAULT*/
		0,/*HOLDING_DIFFERNETIAL_PRESEURE_RANGE_DEFAULT_DEFAULT*/
		0,/*HOLDING_PRESSURE_SPEED_DEFAULT_DEFAULT*/
		0,/*HOLDING_PRESSURE_SPEED_DEFAULT_DEFAULT*/
		0,/*HOLDING_PID_CONFIGURATION_DIFFERNETIAL_TEMPERAUTE_SET_VALUE_DEFAULT*/
		90,/*HOLDING_OVER_WINDING_TEMPERATURE_LIMIT_DEFAULT_VALUE*/
		80,/*HOLDING_RECOVERY_WINDING_TEMPERATURE_LIMIT_DEFAULT_VALUE*/
		0,/*HOLDING_DIFFERNTIAL_TEMPERATURE_SPEED_DEFAULT_DEFAULT*/
		0,/*HOLDING_DIFFERNTIAL_TEMPERATURE_SPEED_DEFAULT_DEFAULT*/
		0,/*HOLDING_PID_CONFIGURE_FLOW_RATE_SET_VALUE_DEFAULT*/
		0,/*HOLDING_FLOW_RATE_RANGE_DEFAULT_DEFAULT*/
		0,/*HOLDING_FLOW_RATE_RANGE_DEFAULT_DEFAULT*/
		0,/*HOLDING_FLOW_SPEED_DEFAULT_DEFAULT*/
		0,/*HOLDING_FLOW_SPEED_DEFAULT_DEFAULT*/
		1,/*HOLDING_K1_FUNCTION_DEFAULT*/
		700,/*HOLDING_SET_INTERNAL_1_DEFAULT*/
		700,/*HOLDING_SET_INTERNAL_2_DEFAULT*/
		700,/*HOLDING_SET_INTERNAL_3_DEFAULT*/
		400,/*HOLDING_DEFAULT_SPEED_DEFAULT*/
		0,/*HOLDING_RESERVED_75_DEFAULT*/
		0,/*HOLDING_CONTROL_BITS_DEFAULT*/
		0,/*HOLDING_RESERVED_77_DEFAULT*/
		1,/*HOLDING_LED_MODE_DEFAULT*/
		0,/*HOLDING_RESERVED_79_DEFAULT*/
		0,/*HOLDING_RESERVED_80_DEFAULT*/
		0,/*HOLDING_RESERVED_81_DEFAULT*/
		0,/*HOLDING_RESERVED_82_DEFAULT*/
		0,/*HOLDING_RESERVED_83_DEFAULT*/
		0,/*HOLDING_RESERVED_84_DEFAULT*/
		0,/*HOLDING_RESERVED_85_DEFAULT*/
		0,/*HOLDING_RESERVED_86_DEFAULT*/
		0,/*HOLDING_RESERVED_87_DEFAULT*/
		0,/*HOLDING_RESERVED_88_DEFAULT*/
		15,/*HOLDING_OVER_CURRENT_LIMIT_DEFAULT*/
		0,/*HOLDING_BLOCKING_PROTECTION_CHANGE_OF_DIRECTION_DEFAULT*/
	  11,/*HOLDING_RECOVERY_CURRENT_LIMIT_DEFAULT*/
		0,/*HOLDING_RESET_DEFAULT*/
		0,/*HOLDING_ANTI_LOCK_RETIES_ROTOR_LOCK_DEFAULT*/
		360,/*HOLDING_OVER_VOLTAGE_LIMIT_DEFAULT*/
		300,/*HOLDING_RECOVERY_OVER_VOLTAGE_LIMIT_DEFAULT*/
		0,/*HOLDING_SENSOR_PRESSURE_UNIT_DEFAULT*/
		0,/*HOLDING_SENSOR_TEMPERATURE_UNIT_DEFAULT*/
		0,/*HOLDING_SENSOR_FLOW_UNIT_DEFAULT*/
		80,/*HOLDING_UNDER_VOLTAGE_FAULT_LIMIT_DEFAULT*/
		150,/*HOLDING_RECOVERY_VOLTAGE_FAULT_LIMIT_DEFAULT*/
		6000,/*HOLDING_OVER_LOAD_LIMIT_DEFAULT*/
		5700,/*HOLDING_RECOVERY_OVER_LOAD_LIMIT_DEFAULT*/
		2500,/*HOLDING_OVER_SPEED_LIMIT_DEFAULT*/
		0,/*HOLDING_MOTOR_MODEL_NAME_104_DEFAULT*/
		0,/*HOLDING_MOTOR_MODEL_NAME_105_DEFAULT*/
		0,/*HOLDING_MOTOR_MODEL_NAME_106_DEFAULT*/
		0,/*HOLDING_MOTOR_MODEL_NAME_107_DEFAULT*/
		0,/*HOLDING_MOTOR_MODEL_NAME_108_DEFAULT*/
		0,/*HOLDING_MOTOR_MODEL_NAME_109_DEFAULT*/
		0,/*HOLDING_MOTOR_MODEL_NAME_110_DEFAULT*/
		0,/*HOLDING_MOTOR_MODEL_NAME_111_DEFAULT*/
		0,/*HOLDING_MOTOR_MACHINE_NUMBER_112_DEFAULT*/
		0,/*HOLDING_MOTOR_MACHINE_NUMBER_113_DEFAULT*/
		0,/*HOLDING_MOTOR_MACHINE_NUMBER_114_DEFAULT*/
		0,/*HOLDING_MOTOR_MACHINE_NUMBER_115_DEFAULT*/
		0,/*HOLDING_MOTOR_MACHINE_NUMBER_116_DEFAULT*/
		0,/*HOLDING_MOTOR_MACHINE_NUMBER_117_DEFAULT*/
		0,/*HOLDING_MOTOR_PRODUCTION_YEAR_DEFAULT*/
		0,/*HOLDING_MOTOR_PRODUCTION_MONTH_DEFAULT*/
		0,/*HOLDING_MOTOR_PRODUCTION_DAY_DEFAULT*/
		0,/*HOLDING_MODEL_NAME_121_DEFAULT*/
		0,/*HOLDING_MODEL_NAME_122_DEFAULT*/
		0,/*HOLDING_MODEL_NAME_123_DEFAULT*/
		0,/*HOLDING_MODEL_NAME_124_DEFAULT*/
		0,/*HOLDING_MODEL_NAME_125_DEFAULT*/
		0,/*HOLDING_MODEL_NAME_126_DEFAULT*/
		0,/*HOLDING_MODEL_NAME_127_DEFAULT*/
		0,/*HOLDING_MODEL_NAME_128_DEFAULT*/
		0,/*HOLDING_MACHINE_NUMBER_129_DEFAULT*/
		0,/*HOLDING_MACHINE_NUMBER_130_DEFAULT*/
		0,/*HOLDING_MACHINE_NUMBER_131_DEFAULT*/
		0,/*HOLDING_MACHINE_NUMBER_132_DEFAULT*/
		0,/*HOLDING_MACHINE_NUMBER_133_DEFAULT*/
		0,/*HOLDING_MACHINE_NUMBER_134_DEFAULT*/
		0,/*HOLDING_MACHINE_PRODUCTION_YEAR_DEFAULT*/
		0,/*HOLDING_MACHINE_PRODUCITON_MONTH_DEFAULT*/
		0,/*HOLDING_MACHINE_PRODUCITON_DAY_DEFAULT*/
		0,/*HOLDING_RATED_POWER_RATING_DEFAULT*/
		1800,/*HOLDING_RECOVERY_OVER_SPEED_LIMIT_DEFAULT*/
		90,/*HOLDING_OVER_IPM_TEMPERATURE_LIMIT_DEFAULT*/
		12,/*HOLDING_RATED_CURRENT_DEFAULT*/
		80,/*HOLDING_RECOVERY_IPM_TEMPERATURE_LIMIT_DEFAULT*/
		8,/*HOLDING_NO_OF_POLES_DEFAULT*/
		0,/*HOLDING_RESERVED_144_DEFAULT*/
		0,/*HOLDING_RATED_TORQUE_DEFAULT*/
		600,/*HOLDING_DRIVE_INPUT_VOLTAGE_DEFAULT_RANGE_DEFAULT*/
		5700,/*HOLDING_DRIVE_DEFAULTIMUM_OUTPUT_DEFAULT_POWER_DEFAULT*/
		12,/*HOLDING_DRIVE_DEFAULTIMUM_CURRENT_RATING_DEFAULT*/
		60,/*HOLDING_DRIVE_FRQUENCY_DEFAULT_RANGE_DEFAULT*/
		70,/*HOLDING_TEMPERATURE_DEFAULT_WORKING_RANGE_DEFAULT*/
	  70,/*HOLDING_TEMPERATURE_DEFAULT_WORKING_RANGE_DEFAULT*/
		80,/*HOLDING_RANGE_DEFAULT_IGBT_TEMPERATUE_DEFAULT*/
		80,/*HOLDING_RANGE_DEFAULT_IGBT_TEMPERATUE_DEFAULT*/
		720,/*HOLDING_DRIVE_INPUT_VOLTAGE_DEFAULT_RANGE_DEFAULT*/
		50,/*HOLDING_DRIVE_FRQUENCY_DEFAULT_RANGE_DEFAULT*/
		50,/*HOLDING_INPUT_FREQUENCY_DEFAULT_RANGE_DEFAULT*/
		50,/*HOLDING_INPUT_FREQUENCY_DEFAULT_RANE_DEFAULT*/
		55,/*HOLDING_TORQUE_CONSTANT_DEFAULT*/
		0,/*HOLDING_FAIL_SAFE_ON_OFF_DEFAULT*/
		1,/*HOLDING_FAIL_SAFE_RUNNING_DIRECTION_DEFAULT*/
		800,/*HOLDING_FAIL_SAFE_FUNCTION_SET_SPEED_DEFAULT*/
		0,/*HOLDING_FAIL_SAFE_SOURCE_DEFAULT*/
		2,/*HOLDING_FAIL_SAFE_ACTIVATE_SET_VALUE_DEFAULT*/
		163,/*HOLDING_TOTAL_MEMBER_DEFAULT*/
	};
