#ifndef __MODBUS_COMM_H_
#define __MODBUS_COMM_H_


#include <string.h>
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <inttypes.h>
#include <stdarg.h>
#include <stdbool.h>
//#include "a31m22x.h"
//#include "a31m22x_scu.h"

#include "a31m22x_uart.h"
#include "Modbus_Holding_Register.h"
#include "Default_Values.h"


#define	UART_PACKET_TXN_SIZE			255
#define UART_PACKET_RX_SIZE 			512 

#define READ_HOLDING_REGISTER			0x03
#define READ_INPUT_REGISTER				0x04
#define WRITE_SINGLE_REGISTER			0x06
#define WRITE_MULTIPLE_REGISTER   0x10
#define ADDRESS_MIN_RANGE					0x01
#define ADDRESS_MAX_RANGE					0XF8
#define QUANTITY_MIN_RANGE				0x01
#define QUANTITY_MAX_RANGE        0xA7
#define VENDOR_ID_FUC_CODE				0x2B


#define FUNCTION_CODE_EXCEPTION_ERROR  			0x01
#define ADDRESS_CODE_EXCEPTION_ERROR  			0x02
#define SLAVE_ADDRESS_CODE_EXCPTION_ERROR  	0x04
#define DATA_VALUE_CODE_EXCEPTION_ERROR  		0x03

#define INPUT_REGISTER_ADDRESS_RANGE  			9999  // 30001-3999
#define HOLDING_REGISTER_ADDRESS_RANGE 			9999 // 40001-4999
#define DATA_VALUE_VAILD_RANGE  						2000
#define RX_BUFFER_SIZE  										512

#define TIME_OUT  													2
#define MIN_UART_SIZE												7
#define DATA_BEGIN_MULTI										7
#define DATA_BEGIN_SINGEL										4

#define ACCORDING_OLDAPPLICATION 						0
#define ACCORDING_NEWAPPLICATION 						1

typedef enum{
	DATA_RECEIVING = 0,
	DATA_RECEIVED_COMPLETED,
	DATA_TO_BE_TRANSMITTED,
	DATA_TRANSMITED_COMPLETED,
}MODBUS_STATMACHINE_t;

typedef struct
{
	uint16_t TRANSMISSION_BUFFER_LENGTH;
	char TRANSMISSION_BUFFER[UART_PACKET_TXN_SIZE];
	uint16_t RECEPTION_BUFFER_LENGTH;
	uint8_t RECEPTION_BUFFER;
	uint8_t RX_Counter;
	uint8_t MODBUS_RECEIVED_BUFFER[UART_PACKET_RX_SIZE];
	uint8_t TOTAL_BYTES_RECEIVED;
	bool DATA_RECEIVED_FLAG;
}LOGGER_t;



typedef enum{
	SLAVE_ID_RX=0,
	FUNCTION_CODE_RX ,
	START_ADDRESS_HIGH_RX,
	START_ADDRESS_LOW_RX,
	REGISTER_QUANTITY_HIGH_RX,
	REGISTER_QUANTITY_LOW_RX,
	CRC_HIGH_RX,
	CRC_LOW_RX,
}MODBUS_FORMAT;

typedef struct{
	uint8_t Slave_ID;
	uint8_t Function_Code;
	uint8_t Start_Address_High;
	uint8_t Start_Address_Low;
	uint16_t RECEIVED_DATA[RX_BUFFER_SIZE];
	uint8_t Byte_Count;
	uint16_t Holding_Register_receive_Crc;
	uint16_t Input_Register_receive_Crc;
	uint16_t Write_Multiple_Register_receive_Crc;
	uint16_t Write_Single_Register_received_Crc;
	uint16_t START_ADDRESS_RECEIVED;
	uint16_t QUANTITY_REGISTR_RECEIVED;
	bool DATA_COMPLETE_DECODE_FLAG;
}MODBUS_DATA_DECODE_t;







typedef struct{
	uint16_t SLAVE_ID_CHECK;
	uint16_t FUNCTION_CODE_tx;
	uint16_t START_ADDRESS;
	uint16_t T_Quantity_Register; 
	uint16_t RECEIVED_CRC_VALUE;
	uint16_t CALCULATED_CRC_RXN;
	uint16_t BYTE_COUNT_TXN;
	uint16_t CALCULATE_CRC_TXN;
}MODBUS_TXN;



typedef struct{
	uint16_t MODBUS_MOTOR_SW_VERSION;			
	uint16_t MODBUS_DEVICE_ID;			
	uint16_t MODBUS_READ_AC_VOLTAGE;	  //ac voltage		
	uint16_t MODBUS_READ_MOTOR_CURRENT;	  //ac current
	uint16_t MODBUS_READ_DC_VOLTAGE;		//dc voltage
	uint16_t MODBUS_READ_DC_CURRENT;		//dc current	
	uint16_t MODBUS_TARGET_SPEED;			 //Target Speed
	uint16_t MODBUS_FAULT_STATUS;			 //Fault status count
	uint16_t MODBUS_MOTOR_STATUS;			 //Motor Status 
	uint16_t MODBUS_ACTUAL_SPEED;			
	uint16_t MODBUS_MOTOR_TEMPERATURE;			
	uint16_t MODBUS_IPM_TEMPERATURE;			
	uint16_t KW;
	uint16_t KWH;
	uint16_t TORQUE;
	uint16_t LOAD;
	
	uint16_t DESIGNED_MAXIMUM_SPEED;
	uint16_t LED_STATUS;
	uint16_t FAULT_CLEAR_STATUS;
	uint16_t OPERTING_FREQUENCY;
	uint16_t DEFAULT;
}Modbus_Parameter;

/**
* @breif This Enum conatin all the Holding register parameter in accending order...
*
*/
#if ACCORDING_NEWAPPLICATION == 1
typedef enum{
	HOLDING_NODE_ADDRESS = 0,
	HOLDING_BAUD_RATE,
	HOLDING_PARITY_SET,
	HOLDING_STOP_BIT,
	HOLDING_CONTROL_MODE,
	HOLDING_FAN_ROTATION,
	HOLDING_MAXIMUM_SPEED,
	HOLDING_MIN_SPEED,
	HOLDING_RAMPUPTIME,
	HOLDING_RAMPDOWNTIME,
	HOLDING_Reserved1,
	HOLDING_Reserved2,
	HOLDING_MIN_RUN_SPEED,
	HOLDING_AI1_MINIMUM_VALUE,
	HOLDING_AI1_MAXIMUM_VALUE,
	HOLDING_Reserved3,
	HOLDING_Reserved4,
	HOLDING_TARGET_SPEED_FROM_MODBUS,
	HOLDING_SET_SPEED_IN_MODBUS_SIGNAL_LOSS_MODE,
	HOLDING_CONTROL_BITS,
	HOLDING_SET_INTERNAL_ACTIVE,
	HOLDING_SET_INTERNAL_1,
	HOLDING_SET_INTERNAL_2,
	HOLDING_SET_INTERNAL_3,
	HOLDING_Reserved,
	HOLDING_Reserved5,
	HOLDING_Reserved6,
	HOLDING_TARGET_SET_POINT,
	HOLDING_Kp_CONSTANT,
	HOLDING_ki_CONSTANT,
	HOLDING_CONTROL_SIGNAL_MAX_LIMIT,
	HOLDING_CONTROL_SIGNAL_MIN_LIMIT,
	HOLDING_PID_SENSOR_SELECT,
	HOLDING_Reserved8,
	HOLDING_Reserved9,
	HOLDING_FIRE_ALARM_ACTIVATE,
	HOLDING_FIRE_ALARM_MODE_SOURCE,
	HOLDING_FIRE_ALARM_CONTROL_SOURCE,
	HOLDING_SET_SPEED_IN_FIRE_ALARAM_MODE,
	HOLDING_Reserved10,
	HOLDING_Reserved11,
	HOLDING_Reserved12,
	HOLDING_SET_FILTER_RUN_HOURS,
	HOLDING_RESET_FILTER_RUN_HOURS,
	HOLDING_Reserved13,
	HOLDING_Reserved14,
	HOLDING_Reserved15,
	HOLDING_DI1_FUNCTION,
	HOLDING_Fail_FUNCTIONACTIVE,
	HOLDING_FAIL_SAFE_SOURCE,
	HOLDING_FAIL_SAFE_FUNCTION_SET_SPEED,
	HOLDING_FAIL_SAFE_RUNNING_DIRECTION,
	HOLDING_Fail_SAFE_ACTIVATE_AT_SET_VALUE,
	HOLDING_Reserved116,
	HOLDING_SUPPRESSION_RANGE_SETTING,
	HOLDING_RANGE_UPPER_VOLTAGE_MIN,
	HOLDING_RANGE_UPPER_VOLTAGE_MAX,
	HOLDING_RANGE_LOWER_VOLTAGE_MIN,
	HOLDING_RANGE_LOWER_VOLTAGE_MAX,
	HOLDING_RANGE_MIN_WINDING_TEMPERATUE,
	HOLDING_RANGE_MAX_WINDING_TEMPERATUE,
	HOLDING_RANGE_MIN_IGBT_TEMPERATUE,
	HOLDING_RANGE_MAX_IGBT_TEMPERATUE,
	HOLDING_RANGE_MIN_MOTOR_CURRENT,
	HOLDING_RANGE_MAX_MOTOR_CURRENT,
	HOLDING_RANGE_UPPER_AMBIENT_TEMPERATURE_MIN,
	HOLDING_RANGE_UPPER_AMBIENT_TEMPERATURE_MAX,
	HOLDING_RANGE_LOWER_AMBIENT_TEMPERATURE_MIN,
	HOLDING_RANGE_LOWER_AMBIENT_TEMPERATURE_MAX,
	HOLDING_RANGE_OVERPOWER_MIN,
	HOLDING_RANGE_OVERPOWER_MAX,
	HOLDING_SUPPRESION_RAMPRATE,
	HOLDING_Reserved18,
	HOLDING_CURRENTCUTOFF_LIMIT,
	HOLDING_UNDER_VOLTAGE_FAULT_LIMIT,
	HOLDING_OVER_LOAD_LIMIT,
	HOLDING_OVER_SPEED_LIMIT,
	HOLDING_OVER_IPM_TEMPERATURE_LIMIT,
	HOLDING_OVER_LIMIT_WINDING_TEMPERATURE,
	HOLDING_OVER_RMS_VOLTAGE_LIMIT,
	HOLDING_UNDER_RMS_VOLTAGE_LIMIT,
	HOLDING_Reserved19,
	HOLDING_Reserved20,
	HOLDING_Reserved21,
	HOLDING_Reserved22,
	HOLDING_RECOVERY_OVER_VOLTAGE_LIMIT,
	HOLDING_RECOVERY_UNDER_VOLTAGE_LIMIT,
	HOLDING_RECOVERY_OVERLOAD_FAULT_LIMIT,
	HOLDING_RECOVERY_SPEED_FAULT_LIMIT,
	HOLDING_ANTI_LOCK_RETIES_ROTOR_LOCK,
	HOLDING_RECOVERY_IPM_TEMPERATURE_LIMIT,
	HOLDING_RECOVERY_LIMIT_WINDING_TEMPERATURE,
	HOLDING_RECOVERY_AC_OVER_VOLTAGE_LIMIT,
	HOLDING_RECOVERY_AC_UNDER_VOLTAGE_FAULT_LIMIT,
	HOLDING_Reserved23,
	HOLDING_Reserved24,
	HOLDING_Reserved25,
	HOLDING_Reserved26,
	HOLDING_FAULTCHECK,
	HOLDING_RESETFAULT,
	HOLDING_Reserved27,
	HOLDING_LEDMODE,
	HOLDING_K1FUNCITON,
	HOLDING_VIBRATIONSENSOR1,
	HOLDING_VIBRATIONSENSOR2,
	HOLDING_VIBRATIONSENSOR3,
	HOLDING_VIBRATIONSENSOR4,
	HOLDING_VIBRATIONSENSOR5,
	HOLDING_VIBRATIONSENSOR6,
	HOLDING_VIBRATIONSENSOR7,
	HOLDING_VIBRATIONSENSOR8,
	HOLDING_VIBRATIONSENSOR9,
	HOLDING_VIBRATIONSENSOR10,
	HOLDING_VIBRATIONSENSOR11,
	HOLDING_VIBRATIONSENSOR12,
	HOLDING_VIBRATIONSENSOR13,
	HOLDING_VIBRATIONSENSOR14,
	HOLDING_VIBRATIONSENSOR15,
	HOLDING_MOTORMODEL1,
	HOLDING_MOTORMODEL2,
	HOLDING_MOTORMODEL3,
	HOLDING_MOTORMODEL4,
	HOLDING_MOTORMODEL5,
	HOLDING_MOTORMODEL6,
	HOLDING_MOTORMODEL7,
	HOLDING_MOTORMODEL8,
	HOLDING_MOTORMACHINE1,
	HOLDING_MOTORMACHINE2,
	HOLDING_MOTORMACHINE3,
	HOLDING_MOTORMACHINE4,
	HOLDING_MOTORMACHINE5,
	HOLDING_MOTORMACHINE6,
	HOLDING_MOTORPRODUCTION_YEAR,
	HOLDING_MOTORPRODUCTION_MONTH,
	HOLDING_MOTORPRODUCTION_DAY,
	HOLDING_DRIVEMODELNAME1,
	HOLDING_DRIVEMODELNAME2,
	HOLDING_DRIVEMODELNAME3,
	HOLDING_DRIVEMODELNAME4,
	HOLDING_DRIVEMODELNAME5,
	HOLDING_DRIVEMODELNAME6,
	HOLDING_DRIVEMODELNAME7,
	HOLDING_DRIVEMODELNAME8,
	HOLDING_DRIVEMACHINENUMBER1,
	HOLDING_DRIVEMACHINENUMBER2,
	HOLDING_DRIVEMACHINENUMBER3,
	HOLDING_DRIVEMACHINENUMBER4,
	HOLDING_DRIVEMACHINENUMBER5,
	HOLDING_DRIVEMACHINENUMBER6,
	HOLDING_DRIVEPRODUCTION_YEAR,
	HOLDING_DRIVEPRODUCITON_MONTH,
	HOLDING_DRIVEPRODUCITON_DAY,
	HOLDING_RATEDCURRENT,
	HOLDING_DRIVE_INPUT_VOLTAGE_MIN_RANGE,
	HOLDING_DRIVE_INPUT_VOLTAGE_MAX_RANGE,
	HOLDING_DRIVE_MAXIMUM_CURRENT_RATING,
	HOLDING_DRIVE_MAXIMUM_OUTPUT_MAX_POWER,
	HOLDING_DRIVE_FRQUENCY_MAX_RANGE,
	HOLDING_DRIVE_FRQUENCY_MIN_RANGE,
	HOLDING_INPUT_FREQUENCY_MAX_RANGE,
	HOLDING_INPUT_FREQUENCY_MIN_RANE,
	HOLDING_POWER_RATING,
	HOLDING_Reserved28,
	HOLDING_Reserved29,
	HOLDING_LINE_INPUT_FREQUENCY_MIN,
	HOLDING_LINE_INPUT_FREQUENCY_MAX,
	HOLDING_NO_OF_POLES,
	HOLDING_TORQUE_CONSTANT,
	HOLDING_Reserved30,
	HOLDING_Reserved31,
	HOLDING_Reserved35,
	HOLDING_Reserved39,
	HOLDING_Reserved36,
	HOLDING_FLASHWRITING,
	HOLDING_SET_DEFAULT_FACTORY,
	HOLDING_Reserved32, 
	HOLDING_Reserved33, 
	HOLDING_SWITCHINGFREQUENCY,
	HOLDING_BLOCKING_PROTECTION_CHANGE_OF_DIRECTION,
	HOLDING_Reserved40,
	HOLDING_Reserved41,
	HOLDING_STATIC_PRESSURE_FILTER_CHOKE,
	HOLDING_SET_REMAINING_HOUR,
	HOLDING_TOTAL_MEMBER,
}HOLDING_PARAMETER_t;
#endif

#if ACCORDING_OLDAPPLICATION == 1
typedef enum{
	  HOLDING_NODE_ADDRESS=0,
		HOLDING_BAUD_RATE,
		HOLDING_PARITY_SET,
		HOLDING_STOP_BIT,
		HOLDING_CONTROL_MODE,
		HOLDING_SET_SPEED_IN_MODBUS_SIGNAL_LOSS_MODE,
		HOLDING_SET_SPEED_IN_FIRE_ALARAM_MODE,
		HOLDING_MAXIMUM_SPEED,
		HOLDING_TARGET_SPEED_FROM_MODBUS,
		HOLDING_FAN_ROTATION,
		HOLDING_RAMP_UP_TIME,
		HOLDING_RAMP_DOWN_TIME,
		HOLDING_FIRE_ALARM_MODE_SOURCE,
		HOLDING_FIRE_ALARM_ACTIVATE,
		HOLDING_DI1_FUNCTION,
		HOLDING_DI2_FUNCTION,
		HOLDING_SET_FILTER_RUN_HOURS,
		HOLDING_RESET_FILTER_RUN_HOURS,
		HOLDING_AI1_MINIMUM_VALUE,
		HOLDING_SWITCHING_FREQUENCY,
		HOLDING_AI1_MAXIMUM_VALUE,
		HOLDING_PID_SENSOR_SELECT,     //PID REGISTER 
		HOLDING_FLASH_WRITING,
		HOLDING_RESET_EVENTS,
		HOLDING_RESERVED_25,
		HOLDING_RESERVED_26,
		HOLDING_RESERVED_27,
		HOLDING_RESERVED_28,
		HOLDING_RESERVED_29,
		HOLDING_RESERVED_30,
		HOLDING_SET_DEFAULT_FACTORY,
		HOLDING_V_FREQUNECY_REG_1,
		HOLDING_V_FREQUNECY_REG_2,
		HOLDING_V_FREQUNECY_REG_3,
		HOLDING_V_FREQUNECY_REG_4,
		HOLDING_V_FREQUNECY_REG_5,
		HOLDING_V_FREQUNECY_REG_6,
		HOLDING_V_FREQUNECY_REG_7,
		HOLDING_V_FREQUNECY_REG_8,
		HOLDING_V_FREQUNECY_REG_9,
		HOLDING_V_FREQUNECY_REG_10,
		HOLDING_V_FREQUNECY_REG_11,
		HOLDING_V_FREQUNECY_REG_12,
		HOLDING_V_FREQUNECY_REG_13,
		HOLDING_V_FREQUNECY_REG_14,
		HOLDING_V_FREQUNECY_REG_15,
		HOLDING_BMS_FUNCTION,
		HOLDING_SUPPRESSION_RANGE_SETTING,
		HOLDING_RANGE_MIN_VOLTAGE,
		HOLDING_RANGE_MAX_VOLTAGE,
		HOLDING_RANGE_MIN_WINDING_TEMPERATUE,
		HOLDING_RANGE_MAX_WINDING_TEMPERATUE,
		HOLDING_RANGE_MIN_MOTOR_CURRENT,
		HOLDING_RANGE_MAX_MOTOR_CURRENT,
		HOLDING_PID_CONFIGURATION_DIFFERENTIAL_PRESSURE_SET_VALUE,
		HOLDING_DIFFERENTIAL_PRESSURE_RANGE_MIN,
		HOLDING_DIFFERNETIAL_PRESEURE_RANGE_MAX,
		HOLDING_PRESSURE_SPEED_MIN,
		HOLDING_PRESSURE_SPEED_MAX,
		HOLDING_PID_CONFIGURATION_DIFFERNETIAL_TEMPERAUTE_SET_VALUE,
		HOLDING_OVER_LIMIT_WINDING_TEMPERATURE,   		//Over winding Tempetaute limit
		HOLDING_RECOVERY_LIMIT_WINDING_TEMPERATURE,   // Recovery winding Temperture limit
		HOLDING_DIFFERNTIAL_TEMPERATURE_SPEED_MIN,
		HOLDING_DIFFERNTIAL_TEMPERATURE_SPEED_MAX,
		HOLDING_PID_CONFIGURE_FLOW_RATE_SET_VALUE,
		HOLDING_FLOW_RATE_RANGE_MIN,
		HOLDING_FLOW_RATE_RANGE_MAX,
		HOLDING_FLOW_SPEED_MIN,
		HOLDING_FLOW_SPEED_MAX,
		HOLDING_K1_FUNCTION,
		HOLDING_SET_INTERNAL_1,
		HOLDING_SET_INTERNAL_2,
		HOLDING_SET_INTERNAL_3,
		HOLDING_MIN_SPEED,
		HOLDING_FAULT_CHECK,
		HOLDING_CONTROL_BITS,
		HOLDING_SET_INTERNAL_ACTIVE,
		HOLDING_LED_MODE,
		HOLDING_DISABLE_TEMP_MANAGEMENT,
		HOLDING_RESERVED_80,
		HOLDING_RESERVED_81,
		HOLDING_RESERVED_82,
		HOLDING_RESERVED_83,
		HOLDING_RESERVED_84,
		HOLDING_RESERVED_85,
		HOLDING_RESERVED_86,
		HOLDING_RESERVED_87,
		HOLDING_RESERVED_88,
		HOLDING_OVER_CURRENT_LIMIT,												//over current limit
		HOLDING_BLOCKING_PROTECTION_CHANGE_OF_DIRECTION,
		HOLDING_RECOVERY_CURRENT_LIMIT,										//Recovery over current limit
		HOLDING_RESET_FAULTS,
		HOLDING_ANTI_LOCK_RETIES_ROTOR_LOCK,
		HOLDING_OVER_VOLTAGE_LIMIT, 											//Over voltage Limit
		HOLDING_RECOVERY_OVER_VOLTAGE_LIMIT, 									//Recovery over voltage limit
		HOLDING_SENSOR_PRESSURE_UNIT,
		HOLDING_SENSOR_TEMPERATURE_UNIT,
		HOLDING_SENSOR_FLOW_UNIT,
		HOLDING_UNDER_VOLTAGE_FAULT_LIMIT, //Under voltage limit
		HOLDING_RECOVERY_VOLTAGE_FAULT_LIMIT, // Recovery Under voltage limit
		HOLDING_OVER_LOAD_LIMIT, // Over load limit
		HOLDING_RECOVERY_OVER_LOAD_LIMIT, // Recovery Over load limit
		HOLDING_OVER_SPEED_LIMIT, // Over Speed limit
		HOLDING_MOTOR_MODEL_NAME_104, 
		HOLDING_MOTOR_MODEL_NAME_105,
		HOLDING_MOTOR_MODEL_NAME_106,
		HOLDING_MOTOR_MODEL_NAME_107,
		HOLDING_MOTOR_MODEL_NAME_108,
		HOLDING_MOTOR_MODEL_NAME_109,
		HOLDING_MOTOR_MODEL_NAME_110,
		HOLDING_MOTOR_MODEL_NAME_111,
		HOLDING_MOTOR_MACHINE_NUMBER_112,
		HOLDING_MOTOR_MACHINE_NUMBER_113,
		HOLDING_MOTOR_MACHINE_NUMBER_114,
		HOLDING_MOTOR_MACHINE_NUMBER_115,
		HOLDING_MOTOR_MACHINE_NUMBER_116,
		HOLDING_MOTOR_MACHINE_NUMBER_117,
		HOLDING_MOTOR_PRODUCTION_YEAR,
		HOLDING_MOTOR_PRODUCTION_MONTH,
		HOLDING_MOTOR_PRODUCTION_DAY,
		HOLDING_MODEL_NAME_121,
		HOLDING_MODEL_NAME_122,
		HOLDING_MODEL_NAME_123,
		HOLDING_MODEL_NAME_124,
		HOLDING_MODEL_NAME_125,
		HOLDING_MODEL_NAME_126,
		HOLDING_MODEL_NAME_127,
		HOLDING_MODEL_NAME_128,
		HOLDING_MACHINE_NUMBER_129,
		HOLDING_MACHINE_NUMBER_130,
		HOLDING_MACHINE_NUMBER_131,
		HOLDING_MACHINE_NUMBER_132,
		HOLDING_MACHINE_NUMBER_133,
		HOLDING_MACHINE_NUMBER_134,
		HOLDING_MACHINE_PRODUCTION_YEAR,
		HOLDING_MACHINE_PRODUCITON_MONTH,
		HOLDING_MACHINE_PRODUCITON_DAY,
		HOLDING_RATED_POWER_RATING,
		HOLDING_RECOVERY_OVER_SPEED_LIMIT,    //Recovery Over speed limit
		HOLDING_OVER_IPM_TEMPERATURE_LIMIT,    //Over ipm temperature limit
		HOLDING_RATED_CURRENT,
		HOLDING_RECOVERY_IPM_TEMPERATURE_LIMIT,   // Recovery ipm temperature limit
		HOLDING_NO_OF_POLES,
		HOLDING_RESERVED_144,   
		HOLDING_RATED_TORQUE,
		HOLDING_DRIVE_INPUT_VOLTAGE_MIN_RANGE,
		HOLDING_DRIVE_MAXIMUM_OUTPUT_MAX_POWER,
		HOLDING_DRIVE_MAXIMUM_CURRENT_RATING,
		HOLDING_DRIVE_FRQUENCY_MAX_RANGE,
		HOLIDNG_TEMPERATURE_MIN_WORKING_RANGE,
		HOLIDNG_TEMPERATURE_MAX_WORKING_RANGE,
		HOLDING_RANGE_MIN_IGBT_TEMPERATUE,
		HOLDING_RANGE_MAX_IGBT_TEMPERATUE,
		HOLDING_DRIVE_INPUT_VOLTAGE_MAX_RANGE,
		HOLDING_DRIVE_FRQUENCY_MIN_RANGE,
		HOLDING_INPUT_FREQUENCY_MAX_RANGE,
		HOLIDNG_INPUT_FREQUENCY_MIN_RANE,
		HOLIDNG_TORQUE_CONSTANT,
		HOLDING_FAIL_SAFE_ON_OFF,
		HOLDING_FAIL_SAFE_RUNNING_DIRECTION,
		HOLDING_FAIL_SAFE_FUNCTION_SET_SPEED,
		HOLDING_FAIL_SAFE_SOURCE,
		HOLDING_FAIL_SAFE_ACTIVATE_SET_VALUE,
		HOLDING_TOTAL_MEMBER,
}HOLDING_PARAMETER_t;
#endif
/**
* @breif This structure conation Input Register parameter in accending order.....
*
*/

typedef enum{
		INPUT_MOTOR_STATUS =0,														
		INPUT_FAULT_CODE,																	
		INPUT_MOTOR_SPEED,																			
		INPUT_MOTOR_CURRENT,																		
		INPUT_DC_VOLTAGE,	
		INPUT_KW,																								
		INPUT_WINDING_TEMPERATURE,
		INPUT_IGBT_TEMPERATURE,    
		INPUT_POWER_ON_HOURS,
		INPUT_RUN_HOURS,
		INPUT_DI1_STATUS,
		INPUT_KWH,
		INPUT_RESERVED_13,
		INPUT_TARGET_SPEED_MODBUS,
		INPUT_FIRE_STATUS,
		INPUT_FAIL_SAFE_STATUS,
		INPUT_FILTER_STATUS,
		INPUT_FILTER_RUN_HOURS,
		INPUT_AI1_VALUE,
		INPUT_AI1_CALCULATED_VALUE,
		INPUT_AI2_VALUE,
		INPUT_AI2_CALCULATED_VALUE,
		INPUT_TACHO_OUT,
		INPUT_A_OUT,
		INPUT_LAST_ERROR_CODE_1ST,
		INPUT_LAST_ERROR_CODE_2ND,
		INPUT_LAST_ERROR_CODE_3RD,
		INPUT_LAST_ERROR_CODE_4TH_TIME,
		INPUT_X_AXIS_VIBRATION,
		INPUT_Y_AXIS_VIBRATION,
		INPUT_Z_AXIS_VIBRATION,
		INPUT_G_VALUE_VIBRATION,
		INPUT_RESERVED_33,
		INPUT_RESERVED_34,
		INPUT_RESERVED_35,
		INPUT_RESERVED_36,
		INPUT_RESERVED_37,
		INPUT_RESERVED_38,
		INPUT_RESERVED_39,
		INPUT_RESERVED_40,
		INPUT_RESERVED_41,
		INPUT_RESERVED_42,
		INPUT_RESERVED_43,
		INPUT_RESERVED_44,
		INPUT_RESERVED_45,
		INPUT_RESERVED_46,
		INPUT_RESERVED_47,
		INPUT_RESERVED_48,
		INPUT_RESERVED_49,
		INPUT_TORQUE,																						
		INPUT_LOAD,																								
		INPUT_OPERATING_FREQUENCY,																
		INPUT_ACUTAL_MOTOR_SPEED_RATED,		
		INPUT_TOTAL_MEMBERS,
}INPUT_PARAMETER_t;

/**
* @breif This structure define the  max , min , actual value of Holding and Input Register .......
*
*/
typedef struct MODBUS_REG_t
{
	uint16_t actual_value;
	uint16_t max_valid_value;
	uint16_t min_valid_value;
}MODBUS_REG_t;//[INPUT_TOTAL_MEMBERS];

extern MODBUS_REG_t MODBUS_INPUT_REGISTERS[INPUT_TOTAL_MEMBERS];
extern MODBUS_REG_t MODBUS_HOLDING_REGISTERS[HOLDING_TOTAL_MEMBER];
extern MODBUS_DATA_DECODE_t Modbus_Decode_Data;
extern LOGGER_t data_logger;
extern Modbus_Parameter modbus_parameter;

extern bool MODBUS_FAULT_OCCUR;


extern uint16_t UART_RX_SIZE;
void ReDeModbus(void);
void ModbusStateMachine(void);
bool CheckTransmitValidData(void);
void UserRs485init(void);
void TransmitData(void);
void init_logging(void);
void erase_log_buffer(void);
void debug_log(const char *fmt, ...);
void print_log(void);
bool ModbusRxDataDecode(void);
bool ModbusDataValidCheck(void);
bool DataReceivedValid(void);
bool INPUT_REGISTER(void);
bool RECEIVED_MODBUS_DATA(void);
void MODBUS_STATEMACHINE(void);
void INPUT_REG_MAXIMUM_RANGE_VALUE(void);
//bool VENDOR_DATA(void);
uint16_t Modbus_CRC16(uint8_t *buffer, uint16_t length);
#endif




